name: Build and Push to GHCR

on:
  push:
    branches:
      - main # Or any branch you want this to run on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker image tag
      id: set-tag
      run: echo "::set-output name=tag::ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):${GITHUB_RUN_NUMBER}"

    - name: Build and push Docker image (api-proflyt)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.set-tag.outputs.tag }}
